# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Justin Oblak | Engineering & security leader
email: hello@justinoblak.com
description: >
  Justin Oblak is a New York City based engineer, architect, team builder, and breaker. 
  He has a proven track record of building and scaling engineering teams
keywords: "Justin Oblak, Justin, Oblak, Software Engineer, Developer, New York City, VP of Engineering, DgDean, Teampay, security, pentest, penetration testing, hacking, white hat, white hat hacking, consulting, consultant, leader, VP, Directory"
baseurl: ""
url: "https://www.justinoblak.com"
twitter_username: jroblak
github_username:  jroblak
twitter:
  username: jroblak
logo: /img/logo2.png
social:
  name: Justin Oblak
  links:
    - https://twitter.com/jroblak
    - https://www.facebook.com/oblak
    - https://www.linkedin.com/in/justinoblak
    - https://github.com/jroblak
    - https://keybase.io/jroblak
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  reviews:
    output: true
    sort_by: score
  essays:
    output: true
  writeups:
    output: true
  predictions:
    output: true
    sort_by: who

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
